"""Auto migration

Revision ID: 21cbb8a3f720
Revises: 
Create Date: 2025-05-20 20:58:02.858518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cbb8a3f720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone_whatsapp_business', sa.String(length=20), nullable=True),
    sa.Column('tipo_estabelecimento', sa.String(length=50), nullable=True),
    sa.Column('integrar_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('modo_operacao', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('setup_completo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_painel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('funcao', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('data_ativacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.Column('plano_assinatura', sa.String(length=50), nullable=True),
    sa.Column('integracoes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario_painel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    op.drop_table('usuario_painel')
    op.drop_table('estabelecimento')
    # ### end Alembic commands ###
